#+TITLE: Run Outreach in development environment
#+Author: VLEAD
#+Date: [2016-05-05 Thu]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil

* Creation of database
  - Login to mysql
    #+BEGIN_EXAMPLE
    mysql -u <username> -p<password>
    #+END_EXAMPLE
  - Show all databases
    #+BEGIN_EXAMPLE
    show databases;
    #+END_EXAMPLE
  - If <outreach> database is present, drop it and create it
    #+BEGIN_EXAMPLE
    drop database outreach
    create database outreach
    #+END_EXAMPLE
  
    Exit our of the mysql console

  - Populate the database
    Go through this step if an existing database either in production or
    staging has to be used. 
    
    #+BEGIN_EXAMPLE
    mysql -u root -p outreach < <pathto sql dump file>
    #+END_EXAMPLE
    

* Creation of Virtual Environment

  + Create Virtual Environemnt in the =outreach= directory
  #+BEGIN_EXAMPLE
  virtualenv venv
  #+END_EXAMPLE
  + Activate the Virtual Environment
  #+BEGIN_EXAMPLE
  source venv/bin/activate
  #+END_EXAMPLE


* Setting up dependencies

  Install all the dependencies for running the =outreach= applciation.
  The =setup.py= script is in the =build/code= directory.

  
  #+BEGIN_EXAMPLE
  cd <path to build/code directory>
  python setup.py install
  #+END_EXAMPLE

  If below problem occurs (reference stackoverflow [[http://stackoverflow.com/questions/7475223/mysql-config-not-found-when-installing-mysqldb-python-interface][post]])
  #+BEGIN_EXAMPLE
  oursqlx/oursql.c:8:22: fatal error: pyconfig.h: No such file or directory
  #include "pyconfig.h"
                      ^
  compilation terminated.
  error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  #+END_EXAMPLE

  #+BEGIN_EXAMPLE
  Do the following
  sudo apt-get install libmysqlclient-dev
  sudo apt-get install python-dev
  #+END_EXAMPLE


* Set SQLALCHEMY_DATABASE_URI
  The variable =SQLALCHEMY_DATABASE_URI= has to be set to proper value in
  =build/code/src/config.py= so that the application can use the database.


* Run the application
  
  The application can now be run from the =build/code= directory
  #+BEGIN_EXAMPLE
  cd <path to build/code directory>
  unset http_proxy
  unset https_proxy
  python src/app.py
  #+END_EXAMPLE


* Access the application
  
  The application is accessed at =http://localhost:5000=
