#+AUTHOR: VLEAD
#+TITLE: Scenarios of Outreach Portal
#+DATE: 28-Oct-2015
* Introduction
  This document briefly explains the functions and roles of each user (Admin, Outreach or Nodal coordinator) scenario wise. 
* Admin user
** Scenario 1 : Adding Outreach Coordinator
  - Page 1 : Required fields Name, Email-id, Institute Name
  - Page 2 : Result page on successful/failure of adding new outreach coordinator
** Scenario 2 : Editing Outreach Coordinator
  - Page 3 : Required fields Name, Email-id with ability to edit, new Email-id for the same institute
  - Page 4 : Result page on successful/failure of updating coordinator details
  The admin should be able to assign another person as an outreach coordinator for the same institute. All earlier Nodal coordinator details for that institute should get transferred automatically to the new Outreach Coordinator.
** Scenario 3 : Deleting Outreach Coordinator
  - Page 5 : Page with listing all Outreach Coordinators associated with ==delete== button 
  - Page 6 : Result page on successful/failure of deleting coordinator
  The admin should be able to delete any outreach coordinator and assign a new one. But data pertaining to the old outreach coordinator should be available.
** Scenario 4 : Adding guidance & Materials
  - Page 7 : Required fields Name, fields to upload supported documents (.pdf, .doc, jpg, ppt, xls)
  - Page 8 : Result page on successful/failure of uploading materials
** Scenario 5 : Editing Documents
  - Page 9 : Required fields Name, fields to upload supported documents (.pdf, .doc)
  - Page 10 : Result page on successful/failure of updating documents details

** Scenario 6 : Deleting Documents
  - Page 11 : Page with listing all documents. Should be able to delete one or many documents.
  - Page 12 : Result page on successful/failure of deleting documents

** Scenario 7: Dashboard
  - Page 13 : Admin should be able to view the dashboard with information about:
   - All outreach coordinators
   - All Nodal center coordinators
   - Total number of workshops run with details
   - Total usage per institute
    
* Outreach Coordinator User
** Scenario 7 : Adding Nodal coordinators
  - Page 13 : Required fields to add new nodal coordinator as follows
              - Name of the nodal center
              - Name of the coordinator
              - Email-id
              - Phone number
              *Target section as follows*
              - No of workshops
              - No of participants
              - No of experiments/usage
  - Page 14 : Result page on successful/failure of adding new nodal coordinator
** Scenario 8 : Deleting Nodal coordinators
  - Page 15 : Can delete one or many nodal coordinators. Page with listing all nodal coordinators associate with delete button
  - Page 16 : Result page on successful/failure of deleting nodal coordinator
** Scenario 9 : Editing Nodal coordinators
  - Page 17 : Page with all nodal coordinator's fields as editable
  - Page 18 : Result page on successful/failure of editing nodal coordinator details
** Scenario 10 : Listing out upcoming workshops
  - Page 19 : Page which lists all the upcoming workshops with details like
    date, location, participants planned, institute name and nodal
    center and nodal coordinator.
  - The list should appear chronologically. 
  - The list should be sortable nodal coordinator-wise

** Scenario 11 : Editing upcoming workshops details

** Scenario 12 : Creating new workshops
  - Add details about a new wokshop (same as a nodal coordinator)
  - Add details of old workshops conducted (this will appear as Workshop History after the workshop reports are submitted)
  - These workshop history details should add to the experiments/usage, participants, workshops, and nodal center count.
  - Should be able to add scanned feedback forms for each workshop
  
  - Page 20 : Fields for uploading documents (.pdf or .doc), feedback
    (positive and negative), No of participants attended and no of
    experiments conducted
  - Page 21 : Result page after submitting the above form
** Scenario 13 : Displaying workshop history
  - Page 22 : Page with listing all finished workshops details like
    date, location, participants, experiments, participating institutes,
    nodal center and submitted reports with view.
** Scenario 14 : Listing reports to be approved by outreach coordinator
   - Page 23 : Page with details like date, location, participants,
     experiments, participating institutes, nodal centers and reports
     with its details. Approve button has to be associated with report
     view.
** Scenario 15 : Following has to be listed in Manage Nodal Coordinators
   - View actual workshops
   - Participants and experiments (against target workshops, participants, and experiments) for each Nodal Coordinator
** Scenario 16 : Add new documents to the documents list provided by Admin.  
  - These should be subject to approval by the admin. 
   
* Nodal Coordinator User
** Scenario 17 : Can view and download documents which are uploaded by Admin and Outreach Coordinator 
   - Page 24 : Page has to list all the documents with download link
     Following are the documents :

     - Eligibility-Systems Configuration-Infrastructure,
     - Pre-requisites-for-workshop, Attendance sheet, Feedback form,
     - Virtual Labs Handout, College Report, Sample-workshop-schedule,
     - Virtual Labs Introduction presentation and College Report format
** Scenario 18 : Creating new workshops and Modifiable by Outreach Coordinators
   - Page 25: Required following details to create new workshop
     - Name
     - Location
     - Participating institutes
     - Date
     - No. of participants
     - No of sessions 
     - Duration of sessions 
     - Name of domain/discipline/department
     - Labs planned for workshop and other details

  - Page 26 : Result page on successful/failure of creating new workshop
** Scenario 19 : Cancelling the workshop
  - Page 27 : Page with listing all the upcoming workshops associated with ==cancel== button
  - Page 28 : Result page on successful/failure of cancelling workshop
** Scenario 20 : Upload workshop feedback materials
 - Page 29 : Fields for uploading documents (.pdf or .doc) and images (.png or .jpeg). Should be able to upload multiple documents or multiple pages of same document.
 - Page 30 : Result page on successful/failure uploading above documents
 - Page XX : Upload scanned feedback forms of the workshop
 
** Scenario 21 : History of conducted workshops
 - Page 31 : Page with workshop details like date, location, no of participants and experiments and also which associate with submitted reports. 

