#!/bin/bash

# Absolute path to the scripts directory
SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
#DOC_FOLDER=$(cd ../src/static/uploads && pwd)
DOC_FOLDER="/var/www/src/static/uploads"
DB_NAME="outreach"
DB_PASS="root"

OUT_FILE_NAME="outreachbackup"
VERSION="v0.2.0"
OUT_FILE="$OUT_FILE_NAME-$VERSION.tar"

# stop the services before taking the dump
$SCRIPTS_DIR && ./stop

# take the dump
mysqldump -u root -p$DB_PASS $DB_NAME > $DB_NAME.sql
if [ $? -ne 0 ]; then
  echo "Error: Something went wrong while taking db dump."
  echo "Aborting backup."
  exit 1;
fi

# start back the services
$SCRIPTS_DIR && ./start

tar --append --file=$OUT_FILE $DOC_FOLDER $DB_NAME.sql
if [ $? -ne 0 ]; then
  echo "Error: Something went wrong while tar-ing the static folderdump."
  echo "Aborting backup."
  exit 1;
fi

echo "Backup successful."
exit 0;

