#+TITLE: Outreach Portal
#+AUTHOR: VLEAD
#+DATE: [2015-10-27 Tue]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ./org-templates/level-0.org
#+options: ^:nil


* Introduction
  Outreach portal keeps track of all the outreach activities done to
  promote Virtual Labs. It also acts as a central place where all the
  documents related to workshops/trainings are stored.

* Requirements
<<<<<<< HEAD
  This release (outreach portal - admin release), fulfills the
  following requirements:

  1. Python API that acts as a wrapper to make CRUD operations on the
     entities - users, roles and workshop_documents.
  2. REST API for various applications to perform CRUD operations on
     the entities - users, roles and workshop_documents.
  
* Design & Implementation  
** High Level Design
#+CAPTION: High Level Design Diagram
  [[./diagrams/outreach.svg]]
** [[backend.org][View & Controller]]
** [[./backend.org][REST API & DB Layer]]
* Test Cases
* Provisioning
* Releases
** Admin Release - v2.1.0
   This release will satisfy requirements 2, 4.1, 5.1
   Release Date :: [2015-11-13 Fri]
** Nodal Coordinator Release - v2.2.0
   This release will satisfy requirements  4.4, 5.3, 13, 14, 15
   Release Date :: [2015-11-20 Fri]
** Outreach Coordinator Release - v2.3.0
   This release will satisfy requirements 3, 4.2, 4.3, 5.2, 6, 7, 8, 9, 10, 11
   and 12
   Release Date :: [2015-11-27 Fri]

>>>>>>> master
